# linux
task:
  container:
    image: gcc:latest
  build_script:
    - python --version
    - pip --version
    - cmake --version
    - conan --version
    #- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    #- python get-pip.py
    #- pip install conan
    #- pip install cmake
    #- cmake --version
    - ./build.sh release x64 linux

# vs2015
#task:
#  windows_container:
#    image: cirrusci/windowsservercore:2016
#  build_script:
#    - build release x64 vs2015

# macOS
#task:
#  osx_instance:
#    image: high-sierra-xcode-9.4.1
#  build_script:
#    - ./build.sh release x64 osx